name: ✨ 功能请求
description: 为这个存储库建议一个想法
title: "[FEATURE] "
labels: ["enhancement", "需要分类"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢您提出功能建议！我们重视每一个改进建议，请详细描述您的想法。

  - type: textarea
    id: problem-description
    attributes:
      label: 问题描述
      description: 您的功能请求是否与某个问题相关？请清楚简洁地描述问题是什么
      placeholder: 我在使用时遇到了困扰，因为...
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: 解决方案描述
      description: 清楚简洁地描述您希望实现的功能
      placeholder: 我希望能够...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: 功能类别
      description: 这个功能属于哪个类别？
      options:
        - 性能优化
        - 新平台支持
        - 安全增强
        - 用户体验改进
        - API 功能
        - 配置选项
        - 监控和日志
        - 文档改进
        - 其他
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个功能的优先级如何？
      options:
        - 低 - 有了更好
        - 中 - 会很有用
        - 高 - 非常需要
        - 紧急 - 阻碍使用
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 清楚简洁地描述您考虑过的任何替代解决方案或功能
      placeholder: 我也考虑过...
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: 使用场景
      description: 描述这个功能的具体使用场景和受益用户群体
      placeholder: |
        这个功能将帮助：
        - 开发者在...场景下
        - 企业用户需要...
        - 个人用户想要...
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: 实现想法
      description: 如果您有关于如何实现这个功能的想法，请分享
      placeholder: 可能的实现方式...
    validations:
      required: false

  - type: dropdown
    id: affected-platforms
    attributes:
      label: 涉及平台
      description: 这个功能涉及哪些平台？
      options:
        - 所有平台
        - GitHub
        - GitLab
        - Hugging Face
        - npm
        - PyPI
        - conda
        - 新平台
      multiple: true
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 附加信息
      description: 添加关于功能请求的任何其他信息、截图或示例
      placeholder: 任何有助于理解功能需求的额外信息...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 确认
      description: 在提交之前，请确认以下内容
      options:
        - label: 我已经搜索了现有的 issues，确认这不是重复请求
          required: true
        - label: 我已经阅读了存储库文档，确认此功能尚未存在
          required: true
        - label: 这个功能符合存储库的目标和范围
          required: true
